version: "2"
services:
  plone:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.comments
    environment:
      ADDONS: "eea.comments[test]"
      DEVELOP: "src/eea.comments"
